
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdb?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # ÷∂Ø¥•∑¢≈‰÷√ false
  batch:
    job:
      enabled: false
debug: true

